using System.Reflection;
using RWCustom;
using UnityEngine;

namespace DryCycle.Items.RopeSpear;

/// <summary>
/// Custom RopeSpear climbing. The rope remains our own constrained Verlet rope;
/// this controller only borrows the useful player-side ideas from vanilla VineGrab:
/// attach the main body chunk to the rope centre line, use vineClimbCursor to let
/// the two body chunks counter-rotate naturally, and drive free hands toward the
/// rope rather than suspending the entire slugcat below an invisible spring point.
/// </summary>
internal static class RopeSpearClimbController
{
    private const float GrabConnectionRadius = 2.35f;
    private const float MaxGrabSeparation = 62f;
    private const float ClimbSpeed = 2.65f;
    private const float SpearMountRange = 22f;
    private const float SpearMountStart = 0.965f;
    private const float RopeReaction = 0.12f;

    private static readonly FieldInfo RopeSystemField = typeof(RopeSpear).GetField(
        "_ropeSystem",
        BindingFlags.Instance | BindingFlags.NonPublic);

    internal static bool Update(
        Player player,
        RopeSpear spear,
        ref float normalizedPosition,
        ref float poseCycle)
    {
        RopeSpearRopeSystem rope = GetRopeSystem(spear);
        if (rope == null ||
            !rope.Ready ||
            !spear.RopeActive ||
            spear.mode == Weapon.Mode.Thrown ||
            player == null ||
            player.room != spear.room ||
            player.dead ||
            player.inShortcut ||
            player.enteringShortCut.HasValue)
        {
            ResetVinePose(player);
            return false;
        }

        if (player.input == null || player.input.Length == 0)
        {
            ResetVinePose(player);
            return false;
        }

        // A fresh throw usually puts the physical RopeHandle into the thrower's
        // newly-free hand. The first frame of a deliberate climb transfers that
        // grip to the rope itself so the free endpoint does not follow the player
        // and create a self-referential rope constraint.
        ReleaseAssociatedHandleForClimb(player, spear);

        Player.InputPackage input = player.input[0];
        Player.InputPackage previousInput = player.input.Length > 1
            ? player.input[1]
            : default;

        if (input.jmp && !previousInput.jmp)
        {
            // Match the useful part of vanilla VineGrab's jump release: preserve
            // the current swing and add only a modest launch away from the rope.
            Vector2 releaseDirection = new Vector2(input.x, Mathf.Max(0.45f, input.y));
            if (releaseDirection.sqrMagnitude < 0.01f)
            {
                releaseDirection = Vector2.up;
            }
            releaseDirection.Normalize();

            player.mainBodyChunk.vel += releaseDirection * 3.5f;
            if (player.bodyChunks != null && player.bodyChunks.Length > 1)
            {
                player.bodyChunks[1].vel += releaseDirection * 3f;
            }

            player.vineClimbCursor *= 0.35f;
            return false;
        }

        // Movement on a flexible rope follows the rope's local tangent. This keeps
        // the latest diagonal-rope input fix while leaving spear mounting/standing
        // to the historical vanilla beam handoff used by a7b1855.
        Vector2 climbInput = new Vector2(input.x, input.y);
        float climbAmount = GetClimbAmount(rope, normalizedPosition, climbInput);
        if (Mathf.Abs(climbAmount) > 0.05f)
        {
            normalizedPosition = AdvanceGrabPosition(
                rope,
                normalizedPosition,
                climbAmount);
            poseCycle += 0.22f * Mathf.Abs(climbAmount);
        }
        else
        {
            poseCycle += 0.035f * Mathf.Abs(input.x);
        }

        bool movingTowardSpear = climbAmount > 0.05f;

        // Historical RopeSpear behavior: once the player reaches the spear end,
        // hand control back to the horizontal beam generated by Spear.ChangeMode.
        // From this point vanilla GetUpOnBeam and beam standing own the transition.
        if (movingTowardSpear && TryMountSpearFromRope(player, spear, rope, normalizedPosition))
        {
            player.vineClimbCursor *= 0.2f;
            return false;
        }

        Vector2 ropePoint = rope.GetPoint(normalizedPosition);
        if (!Custom.DistLess(player.mainBodyChunk.pos, ropePoint, MaxGrabSeparation))
        {
            ResetVinePose(player);
            return false;
        }

        // This is the important vanilla VineGrab posture behaviour. The main chunk
        // sits on the vine/rope centreline while the rear body chunk remains free to
        // hang and swing. The old RopeSpear code instead targeted ropePoint-(0,11),
        // which visually suspended the whole slugcat underneath a point.
        ConnectMainChunkToRope(player.mainBodyChunk, rope, normalizedPosition, ropePoint);

        Vector2 inputDirection = player.SwimDir(normalize: true);
        if (inputDirection.sqrMagnitude > 0.0001f)
        {
            Vector2 cursorDirection = player.vineClimbCursor.sqrMagnitude > 0.0001f
                ? player.vineClimbCursor.normalized
                : inputDirection;
            float cursorAcceleration = Custom.LerpMap(
                Vector2.Dot(inputDirection, cursorDirection),
                -1f,
                1f,
                10f,
                3f);
            player.vineClimbCursor = Vector2.ClampMagnitude(
                player.vineClimbCursor + inputDirection * cursorAcceleration,
                30f);
        }
        else
        {
            player.vineClimbCursor *= 0.8f;
        }

        // Vanilla applies these opposite impulses to the two chunks. This small
        // counter-rotation is what makes the slugcat look like it is climbing a
        // flexible object rather than being dragged around by its torso.
        player.mainBodyChunk.vel += player.vineClimbCursor / 190f;
        if (player.bodyChunks != null && player.bodyChunks.Length > 1)
        {
            player.bodyChunks[1].vel -= player.vineClimbCursor / 190f;
        }

        // Horizontal input is swing authority only when it is mostly perpendicular
        // to the rope. On a diagonal rope, horizontal input is already meaningful
        // climbing input and must not simultaneously pull the body away from it.
        if (input.x != 0 && Mathf.Abs(climbAmount) < 0.35f)
        {
            float swing = input.x * 0.085f;
            player.mainBodyChunk.vel.x += swing;
            if (player.bodyChunks != null && player.bodyChunks.Length > 1)
            {
                player.bodyChunks[1].vel.x += swing * 0.7f;
            }
        }

        // RegionKit's climbable rope uses the same guards because ordinary player
        // ledge/wall states otherwise fight a flexible-rope attachment at edges.
        player.bodyMode = Player.BodyModeIndex.Default;
        player.standing = true;
        player.ledgeGrabCounter = 0;
        player.wallSlideCounter = 0;

        rope.ApplyExternalPull(
            normalizedPosition,
            player.mainBodyChunk.pos,
            0.075f);
        return true;
    }

    /// <summary>
    /// A freshly thrown RopeSpear normally puts its RopeHandle into the thrower's
    /// newly-free hand. When that same player deliberately climbs onto the rope,
    /// transfer from the handle to the rope by dropping only the associated handle.
    /// This mirrors physically letting the free end dangle before climbing.
    /// </summary>
    internal static void ReleaseAssociatedHandleForClimb(Player player, RopeSpear spear)
    {
        if (player?.grasps == null || spear?.abstractPhysicalObject == null)
        {
            return;
        }

        EntityID spearId = spear.abstractPhysicalObject.ID;
        for (int i = player.grasps.Length - 1; i >= 0; i--)
        {
            if (player.grasps[i]?.grabbed is RopeHandle handle &&
                handle.ParentSpearID == spearId)
            {
                player.ReleaseGrasp(i);
            }
        }
    }

    internal static void PrepareHands(
        PlayerGraphics graphics,
        RopeSpear spear,
        float normalizedPosition,
        float poseCycle)
    {
        if (graphics?.player == null || graphics.hands == null)
        {
            return;
        }

        RopeSpearRopeSystem rope = GetRopeSystem(spear);
        if (rope == null || !rope.Ready || !spear.RopeActive)
        {
            return;
        }

        GetRopePose(rope, normalizedPosition, out Vector2 point, out Vector2 tangent);

        // Alternate the free hands slightly along the rope as the player climbs.
        // This is deliberately graphics-only; physical attachment still comes from
        // the body chunk constraint above.
        float stride = Mathf.Sin(poseCycle) * 2.6f;
        float[] offsets = { -6.5f + stride, 6.5f - stride };

        for (int i = 0; i < 2 && i < graphics.hands.Length; i++)
        {
            if (graphics.player.grasps != null &&
                i < graphics.player.grasps.Length &&
                graphics.player.grasps[i] != null)
            {
                continue;
            }

            SlugcatHand hand = graphics.hands[i];
            if (hand == null)
            {
                continue;
            }

            hand.mode = Limb.Mode.HuntAbsolutePosition;
            hand.reachingForObject = true;
            hand.absoluteHuntPos = point + tangent * offsets[i];
            hand.huntSpeed = 16f;
            hand.quickness = 0.85f;
        }
    }

    internal static void ResetVinePose(Player player)
    {
        if (player != null)
        {
            player.vineClimbCursor *= 0.35f;
        }
    }

    private static RopeSpearRopeSystem GetRopeSystem(RopeSpear spear)
    {
        return spear == null
            ? null
            : RopeSystemField?.GetValue(spear) as RopeSpearRopeSystem;
    }

    private static void ConnectMainChunkToRope(
        BodyChunk chunk,
        RopeSpearRopeSystem rope,
        float normalizedPosition,
        Vector2 ropePoint)
    {
        float distance = Vector2.Distance(chunk.pos, ropePoint);
        if (distance <= GrabConnectionRadius)
        {
            return;
        }

        Vector2 before = chunk.pos;
        Vector2 direction = Custom.DirVec(chunk.pos, ropePoint);
        Vector2 correction = direction * ((distance - GrabConnectionRadius) * 0.72f);

        chunk.pos += correction;
        chunk.vel += correction;

        // The complementary part of the correction goes into nearby rope nodes.
        // ApplyExternalPull spreads this over several nodes so the player actually
        // loads the rope instead of merely being teleported onto a visual line.
        rope.ApplyExternalPull(
            normalizedPosition,
            before,
            RopeReaction);
    }

    private static float GetClimbAmount(
        RopeSpearRopeSystem rope,
        float current,
        Vector2 input)
    {
        if (rope == null || input.sqrMagnitude < 0.01f)
        {
            return 0f;
        }

        if (input.sqrMagnitude > 1f)
        {
            input.Normalize();
        }

        GetRopePose(rope, current, out _, out Vector2 tangent);
        return Mathf.Clamp(Vector2.Dot(input, tangent), -1f, 1f);
    }

    private static float AdvanceGrabPosition(
        RopeSpearRopeSystem rope,
        float current,
        float climbAmount)
    {
        float referenceLength = Mathf.Max(80f, rope.RouteLength);
        float step = Mathf.Clamp(ClimbSpeed / referenceLength, 0.004f, 0.035f);
        return Mathf.Clamp01(
            current + step * Mathf.Clamp(climbAmount, -1f, 1f));
    }

    private static void GetRopePose(
        RopeSpearRopeSystem rope,
        float normalizedPosition,
        out Vector2 point,
        out Vector2 tangent)
    {
        point = rope.GetPoint(normalizedPosition);
        float sample = 1f / (RopeSpearRopeSystem.NodeCount - 1f);
        Vector2 before = rope.GetPoint(Mathf.Clamp01(normalizedPosition - sample));
        Vector2 after = rope.GetPoint(Mathf.Clamp01(normalizedPosition + sample));
        tangent = after - before;
        if (tangent.sqrMagnitude < 0.0001f)
        {
            tangent = Vector2.up;
        }
        else
        {
            tangent.Normalize();
        }
    }

    private static bool TryMountSpearFromRope(
        Player player,
        RopeSpear spear,
        RopeSpearRopeSystem rope,
        float normalizedPosition)
    {
        if (spear.mode != Weapon.Mode.StuckInWall ||
            spear.abstractPhysicalObject is not AbstractRopeSpear data ||
            data.stuckInWallCycles < 0 ||
            normalizedPosition < SpearMountStart ||
            player.room == null)
        {
            return false;
        }

        Vector2 spearPoint = rope.GetPoint(1f);

        // The player must physically finish the climb. Being near the endpoint in
        // normalized rope space is not enough: the main body itself has to arrive
        // at the spear tail and enter one of the horizontal-beam tiles created by
        // vanilla Spear.ChangeMode(StuckInWall).
        if (!Custom.DistLess(player.mainBodyChunk.pos, spearPoint, SpearMountRange))
        {
            return false;
        }

        Room.Tile bodyTile = player.room.GetTile(player.mainBodyChunk.pos);
        if (!bodyTile.horizontalBeam || bodyTile.Solid)
        {
            return false;
        }

        // Mirror vanilla's own HangFromBeam -> GetUpOnBeam handoff. Crucially, do
        // not write body chunk positions, lastPos, or zero velocities here. The
        // GetUpOnBeam animation moves the cat from its real current position by
        // applying velocity toward upOnHorizontalBeamPos over subsequent frames.
        Vector2 pullupTarget = new Vector2(
            player.mainBodyChunk.pos.x,
            player.room.MiddleOfTile(player.mainBodyChunk.pos).y + 20f);

        if (!Custom.DistLess(player.mainBodyChunk.pos, pullupTarget, 25f))
        {
            return false;
        }

        player.pullupSoftlockSafety = 0;
        player.straightUpOnHorizontalBeam = true;
        player.upOnHorizontalBeamPos = pullupTarget;
        player.standing = false;
        player.animation = Player.AnimationIndex.GetUpOnBeam;

        player.room.PlaySound(
            SoundID.Slugcat_Get_Up_On_Horizontal_Beam,
            player.mainBodyChunk,
            loop: false,
            0.75f,
            1f);
        return true;
    }
}
