using RWCustom;
using UnityEngine;

namespace DryCycle.Creatures.MossySpider;

public sealed class MossySpider : Creature
{
    // Keep the collision skeleton sparse. The visible moss slab is much larger than
    // these four core masses, the same general approach used by Rain Deer/DrillCrab:
    // BodyChunks describe the torso, appendages describe the stance.
    internal const int SegmentCount = 4;
    internal const float SegmentSpacing = 78f;
    internal const int LegCount = 10;

    private const float UnsupportedGravity = 0.90f;
    private const float SupportedGravity = 0.070f;
    private const int MinimumStableFeet = 5;
    private const int MaximumSteppingLegs = 2;

    private static readonly float[] SegmentRadii =
    [
        27f,
        31f,
        31f,
        27f
    ];

    private static readonly float[] SegmentMasses =
    [
        5.8f,
        6.8f,
        6.8f,
        5.8f
    ];

    public float IdleMotion;
    public float LastIdleMotion;

    internal MossySpiderLeg[] SupportLegs { get; }
    internal MossySpiderAI AI => abstractCreature?.abstractAI?.RealAI as MossySpiderAI;

    internal Vector2 MoveDirection { get; private set; }
    internal float SwimFactor { get; private set; }
    internal float GaitCycle { get; private set; }
    internal float GroundSupport { get; private set; }

    private int nextStepLeg;
    private int stepCounter;

    public BodyChunk MiddleChunk => bodyChunks[1];

    internal Vector2 BodyCenter
    {
        get
        {
            Vector2 center = Vector2.zero;
            for (int i = 0; i < bodyChunks.Length; i++)
            {
                center += bodyChunks[i].pos;
            }
            return center / bodyChunks.Length;
        }
    }

    public MossySpider(AbstractCreature abstractCreature, World world) : base(abstractCreature, world)
    {
        bodyChunks = new BodyChunk[SegmentCount];
        for (int i = 0; i < SegmentCount; i++)
        {
            bodyChunks[i] = new BodyChunk(
                this,
                i,
                Vector2.zero,
                SegmentRadii[i],
                SegmentMasses[i]);
            bodyChunks[i].restrictInRoomRange = 2000f;
            bodyChunks[i].defaultRestrictInRoomRange = 2000f;
        }

        // No triangles, braces or angle constraints. Four chunks, three ordinary
        // length connections. Posture is generated by muscle forces and legs.
        bodyChunkConnections = new BodyChunkConnection[SegmentCount - 1];
        for (int i = 0; i < SegmentCount - 1; i++)
        {
            bodyChunkConnections[i] = new BodyChunkConnection(
                bodyChunks[i],
                bodyChunks[i + 1],
                SegmentSpacing,
                BodyChunkConnection.Type.Normal,
                1f,
                -1f);
        }

        bodyChunks[0].rotationChunk = bodyChunks[1];
        bodyChunks[1].rotationChunk = bodyChunks[2];
        bodyChunks[2].rotationChunk = bodyChunks[1];
        bodyChunks[3].rotationChunk = bodyChunks[2];

        // Five leg stations are interpolated across the four-chunk body. Each station
        // has a near/far leg pair. The legs themselves own segmented appendage state;
        // they are not BodyChunk chains and they are not decorative raycast lines.
        SupportLegs = new MossySpiderLeg[LegCount];
        for (int station = 0; station < 5; station++)
        {
            float stationT = station / 4f;
            float bodyU = Mathf.Lerp(0.055f, 0.945f, stationT);
            float standHeight = 108f + Mathf.Sin(stationT * Mathf.PI) * 12f;
            float maxLength = 174f + Mathf.Sin(stationT * Mathf.PI) * 10f;
            float stationFan = Mathf.Lerp(-76f, 76f, stationT);

            for (int layer = 0; layer < 2; layer++)
            {
                int legIndex = station * 2 + layer;
                float pairFan = layer == 0 ? -22f : 22f;

                SupportLegs[legIndex] = new MossySpiderLeg(
                    legIndex,
                    station,
                    layer,
                    bodyU,
                    standHeight,
                    maxLength,
                    stationFan + pairFan);
            }
        }

        airFriction = 0.999f;
        gravity = UnsupportedGravity;
        bounce = 0.05f;
        surfaceFriction = 0.40f;
        collisionLayer = 1;
        waterFriction = 0.96f;
        buoyancy = 0.70f;
        GoThroughFloors = true;
    }

    public override void PlaceInRoom(Room placeRoom)
    {
        base.PlaceInRoom(placeRoom);

        // Give the appendages room to deploy before the torso settles. If a room spawn
        // is already airborne this simply becomes the first falling frame; on a floor
        // it avoids starting with the whole belly embedded in the walking surface.
        Vector2 center = placeRoom.MiddleOfTile(abstractCreature.pos.Tile) + Vector2.up * 88f;
        float half = (SegmentCount - 1) * 0.5f;
        for (int i = 0; i < SegmentCount; i++)
        {
            BodyChunk chunk = bodyChunks[i];
            Vector2 pos = center + Vector2.right * ((i - half) * SegmentSpacing);
            chunk.pos = pos;
            chunk.lastPos = pos;
            chunk.lastLastPos = pos;
            chunk.vel = Vector2.zero;
        }

        ResetLocomotionState();
    }

    public override void NewRoom(Room newRoom)
    {
        base.NewRoom(newRoom);
        ResetLocomotionState();
    }

    public override void InitiateGraphicsModule()
    {
        graphicsModule ??= new MossySpiderGraphics(this);
    }

    public override Color ShortCutColor() => new(0.48f, 0.52f, 0.22f);

    public override void Update(bool eu)
    {
        base.Update(eu);

        rainDeath = 0f;
        LastIdleMotion = IdleMotion;
        IdleMotion = Mathf.Repeat(IdleMotion + 0.013f, 10000f);

        AI?.Update();

        if (room == null)
        {
            gravity = UnsupportedGravity;
            rainDeath = 0f;
            return;
        }

        if (Consious && !dead)
        {
            UpdateLocomotionIntent();
        }
        else
        {
            MoveDirection = Vector2.Lerp(MoveDirection, Vector2.zero, 0.15f);
        }

        Vector2 bodyAxis = PhysicalBodyAxis();
        UpdateGaitClock(bodyAxis);

        // Like DrillCrab, appendages update before the creature decides how much of
        // its weight is currently supported.
        for (int i = 0; i < SupportLegs.Length; i++)
        {
            SupportLegs[i].Update(this, bodyAxis);
        }

        UpdateSwimFactor();

        if (Consious && !dead)
        {
            if (SwimFactor < 0.58f)
            {
                CoordinateGroundGait(bodyAxis);
            }

            ApplyGroundSupport();
            ApplyDorsalFloat();
        }
        else
        {
            gravity = Mathf.MoveTowards(gravity, UnsupportedGravity, 0.05f);
            GroundSupport = Mathf.MoveTowards(GroundSupport, 0f, 0.08f);
        }

        ApplyTorsoMuscles();
        rainDeath = 0f;
    }

    internal Vector2 BodyPointAt(float bodyU)
    {
        float x = Mathf.Clamp01(bodyU) * (bodyChunks.Length - 1);
        int a = Mathf.Clamp(Mathf.FloorToInt(x), 0, bodyChunks.Length - 2);
        float t = x - a;
        return Vector2.Lerp(bodyChunks[a].pos, bodyChunks[a + 1].pos, t);
    }

    internal Vector2 BodyVelocityAt(float bodyU)
    {
        float x = Mathf.Clamp01(bodyU) * (bodyChunks.Length - 1);
        int a = Mathf.Clamp(Mathf.FloorToInt(x), 0, bodyChunks.Length - 2);
        float t = x - a;
        return Vector2.Lerp(bodyChunks[a].vel, bodyChunks[a + 1].vel, t);
    }

    internal void ApplyMomentumAt(float bodyU, Vector2 momentum)
    {
        float x = Mathf.Clamp01(bodyU) * (bodyChunks.Length - 1);
        int a = Mathf.Clamp(Mathf.FloorToInt(x), 0, bodyChunks.Length - 2);
        int b = a + 1;
        float t = x - a;

        bodyChunks[a].vel += momentum * ((1f - t) / Mathf.Max(0.01f, bodyChunks[a].mass));
        bodyChunks[b].vel += momentum * (t / Mathf.Max(0.01f, bodyChunks[b].mass));
    }

    internal int SupportingLegCount()
    {
        int count = 0;
        for (int i = 0; i < SupportLegs.Length; i++)
        {
            if (SupportLegs[i].Supporting)
            {
                count++;
            }
        }
        return count;
    }

    internal void AccessSideSpace(WorldCoordinate start, WorldCoordinate destination)
    {
        if (room?.game?.shortcuts == null)
        {
            return;
        }

        room.game.shortcuts.CreatureTakeFlight(
            this,
            AbstractRoomNode.Type.SideExit,
            start,
            destination);
    }

    private void ResetLocomotionState()
    {
        MoveDirection = Vector2.zero;
        SwimFactor = 0f;
        GroundSupport = 0f;
        GaitCycle = 0f;
        nextStepLeg = 0;
        stepCounter = 0;
        gravity = UnsupportedGravity;
        airFriction = 0.999f;

        Vector2 axis = PhysicalBodyAxis();
        for (int i = 0; i < SupportLegs.Length; i++)
        {
            SupportLegs[i].Reset(this, axis);
        }
    }

    private void UpdateLocomotionIntent()
    {
        if (AI?.Pather == null)
        {
            MoveDirection = Vector2.Lerp(MoveDirection, Vector2.zero, 0.12f);
            return;
        }

        MovementConnection move = AI.Pather.FollowPath(
            room.GetWorldCoordinate(BodyCenter),
            actuallyFollowingThisPath: true);

        if (move == default)
        {
            move = AI.Pather.FollowPath(
                room.GetWorldCoordinate(bodyChunks[1].pos),
                actuallyFollowingThisPath: true);
        }

        if (move == default)
        {
            move = AI.Pather.FollowPath(
                room.GetWorldCoordinate(bodyChunks[2].pos),
                actuallyFollowingThisPath: true);
        }

        if (move == default || !move.destinationCoord.TileDefined)
        {
            MoveDirection = Vector2.Lerp(MoveDirection, Vector2.zero, 0.10f);
            return;
        }

        Vector2 desired = room.MiddleOfTile(move.destinationCoord) - BodyCenter;
        if (desired.sqrMagnitude > 0.001f)
        {
            desired.Normalize();
        }

        if (SwimFactor < 0.55f)
        {
            // Air may be legal to the AI center, but the legs—not the pather—own
            // terrestrial body height.
            desired.y *= 0.12f;
            if (desired.sqrMagnitude > 0.001f)
            {
                desired.Normalize();
            }
        }

        MoveDirection = Vector2.Lerp(MoveDirection, desired, 0.10f);

        float supportDrive = Mathf.Lerp(0.22f, 1f, GroundSupport);
        float drive = Mathf.Lerp(0.050f * supportDrive, 0.064f, SwimFactor);
        float maxHorizontalSpeed = Mathf.Lerp(1.28f, 1.65f, SwimFactor);

        for (int i = 0; i < bodyChunks.Length; i++)
        {
            BodyChunk chunk = bodyChunks[i];
            chunk.vel.x += MoveDirection.x * drive;
            chunk.vel.x = Mathf.Clamp(chunk.vel.x, -maxHorizontalSpeed, maxHorizontalSpeed);

            if (SwimFactor > 0.05f)
            {
                chunk.vel.y += MoveDirection.y * drive * 0.55f * SwimFactor;
            }
        }
    }

    private void UpdateGaitClock(Vector2 bodyAxis)
    {
        float movement = Mathf.Clamp01(Mathf.Abs(Vector2.Dot(MoveDirection, bodyAxis)));
        float actual = Mathf.Clamp01(Mathf.Abs(BodyVelocityAt(0.5f).x) / 1.2f);
        GaitCycle = Mathf.Repeat(
            GaitCycle + Mathf.Lerp(0.001f, 0.017f, Mathf.Max(movement * 0.6f, actual)),
            1f);
    }

    private void CoordinateGroundGait(Vector2 bodyAxis)
    {
        float motion = Mathf.Abs(Vector2.Dot(MoveDirection, bodyAxis));
        if (motion < 0.08f)
        {
            stepCounter = Mathf.Max(0, stepCounter - 1);
            return;
        }

        int stepping = 0;
        for (int i = 0; i < SupportLegs.Length; i++)
        {
            if (SupportLegs[i].Stepping)
            {
                stepping++;
            }
        }

        if (stepping >= MaximumSteppingLegs)
        {
            return;
        }

        stepCounter++;
        if (stepCounter < 8)
        {
            return;
        }
        stepCounter = 0;

        int supporting = SupportingLegCount();
        for (int attempt = 0; attempt < LegCount; attempt++)
        {
            int legIndex = nextStepLeg;
            nextStepLeg = (nextStepLeg + 3) % LegCount;
            MossySpiderLeg leg = SupportLegs[legIndex];

            if (!leg.Supporting || !leg.WantsToStep(this, bodyAxis))
            {
                continue;
            }

            if (supporting - 1 < MinimumStableFeet || StationHasSteppingLeg(leg.Station))
            {
                continue;
            }

            if (leg.StartStep(this, bodyAxis))
            {
                return;
            }
        }
    }

    private bool StationHasSteppingLeg(int station)
    {
        for (int i = 0; i < SupportLegs.Length; i++)
        {
            if (SupportLegs[i].Station == station && SupportLegs[i].Stepping)
            {
                return true;
            }
        }
        return false;
    }

    private void ApplyGroundSupport()
    {
        int supporting = SupportingLegCount();
        float supportTarget = Mathf.InverseLerp(2f, 6f, supporting);
        float groundFactor = 1f - Mathf.SmoothStep(0.48f, 0.90f, SwimFactor);
        supportTarget *= groundFactor;

        GroundSupport = Mathf.Lerp(GroundSupport, supportTarget, 0.18f);
        gravity = Mathf.Lerp(UnsupportedGravity, SupportedGravity, GroundSupport);
        airFriction = Mathf.Lerp(0.999f, 0.955f, GroundSupport);

        if (groundFactor <= 0.001f)
        {
            return;
        }

        for (int i = 0; i < SupportLegs.Length; i++)
        {
            if (SupportLegs[i].Supporting)
            {
                SupportLegs[i].ApplySupportMomentum(this, groundFactor);
            }
        }
    }

    private void UpdateSwimFactor()
    {
        if (!room.water)
        {
            SwimFactor = Mathf.MoveTowards(SwimFactor, 0f, 0.04f);
            return;
        }

        float averageSubmersion = 0f;
        for (int i = 0; i < bodyChunks.Length; i++)
        {
            averageSubmersion += bodyChunks[i].submersion;
        }
        averageSubmersion /= bodyChunks.Length;

        int support = SupportingLegCount();
        float waterFactor = Mathf.InverseLerp(0.12f, 0.55f, averageSubmersion);
        float bottomLost = Mathf.InverseLerp(5f, 1f, support);
        float target = Mathf.Clamp01(waterFactor * bottomLost);
        SwimFactor = Mathf.MoveTowards(SwimFactor, target, 0.025f);
    }

    private void ApplyDorsalFloat()
    {
        if (!room.water || SwimFactor <= 0.001f)
        {
            return;
        }

        gravity = Mathf.Lerp(gravity, 0.04f, SwimFactor);
        float surface = room.FloatWaterLevel(BodyCenter);

        for (int i = 0; i < bodyChunks.Length; i++)
        {
            BodyChunk chunk = bodyChunks[i];
            float dorsalTop = chunk.pos.y + chunk.rad * 0.55f + 24f;
            float error = surface + 2f - dorsalTop;
            float correction = Mathf.Clamp(
                error * 0.012f - chunk.vel.y * 0.070f,
                -0.34f,
                0.52f);
            chunk.vel.y += correction * SwimFactor;
        }
    }

    private void ApplyTorsoMuscles()
    {
        // Deer uses WeightedPush muscle forces rather than extra rigid connections.
        // Only intervene when a two-link span is actually collapsing; ordinary bends,
        // slopes and direct DevTools dragging remain free and have no preferred angle.
        for (int i = 0; i < bodyChunks.Length - 2; i++)
        {
            Vector2 delta = bodyChunks[i + 2].pos - bodyChunks[i].pos;
            float distance = delta.magnitude;
            if (distance < 0.001f)
            {
                continue;
            }

            float collapse = Mathf.InverseLerp(
                SegmentSpacing * 1.72f,
                SegmentSpacing * 0.82f,
                distance);

            if (collapse > 0f)
            {
                WeightedPush(i, i + 2, -delta / distance, collapse * 0.34f);
            }
        }

        for (int i = 0; i < bodyChunks.Length; i++)
        {
            bodyChunks[i].vel.x *= SwimFactor > 0.5f ? 0.998f : 0.996f;
        }
    }

    private Vector2 PhysicalBodyAxis()
    {
        Vector2 axis = bodyChunks[bodyChunks.Length - 1].pos - bodyChunks[0].pos;
        return axis.sqrMagnitude > 0.001f ? axis.normalized : Vector2.right;
    }
}
