<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>13</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../src/DevUI/DevTool/Map/MapViewPersistentCache.cs"
             Link="Production/MapViewPersistentCache.cs" />
  </ItemGroup>
</Project>
